# Generated by Django 5.1.4 on 2026-08-12 05:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('os', 'Sistema operacional'), ('web-server', 'Servidor web'), ('framework', 'Framework'), ('language', 'Linguagem'), ('frontend', 'Frontend'), ('cms', 'CMS'), ('database', 'Banco de dados'), ('tls', 'TLS'), ('other', 'Outro')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(max_length=50)),
                ('evidence', models.TextField(blank=True, default='')),
                ('confidence', models.CharField(choices=[('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa')], default='medium', max_length=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='assets.asset')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('asset', 'category', 'name')},
            },
        ),
    ]
