# Generated by Django 5.1.4 on 2026-08-12 22:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnsRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=255)),
                ('record_type', models.CharField(choices=[('MX', 'MX'), ('NS', 'NS'), ('TXT', 'TXT'), ('SOA', 'SOA'), ('SRV', 'SRV'), ('CNAME', 'CNAME'), ('CAA', 'CAA'), ('PTR', 'PTR')], max_length=10)),
                ('value', models.TextField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_records', to='assets.asset')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('asset', 'record_type', 'value')},
            },
        ),
    ]
