# Generated by Django 5.1.4 on 2026-08-12 03:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vulnerability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cve", models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Crítica"),
                            ("high", "Alta"),
                            ("medium", "Média"),
                            ("low", "Baixa"),
                            ("info", "Informativa"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cvss_score",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
                ),
                ("cvss_vector", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField()),
                ("references", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target", models.CharField(max_length=255)),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("discovery", "Discovery"),
                            ("fingerprint", "Fingerprint"),
                            ("vulnerability", "Vulnerability"),
                            ("full", "Full"),
                        ],
                        default="discovery",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("running", "Executando"),
                            ("completed", "Concluído"),
                            ("failed", "Falhou"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("authorized_by", models.CharField(max_length=255)),
                ("authorization_scope", models.TextField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Crítica"),
                            ("high", "Alta"),
                            ("medium", "Média"),
                            ("low", "Baixa"),
                            ("info", "Informativa"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cvss",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
                ),
                ("description", models.TextField()),
                ("evidence", models.TextField()),
                ("recommendation", models.TextField()),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="findings",
                        to="assets.asset",
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="findings",
                        to="scans.scan",
                    ),
                ),
                (
                    "vulnerability",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="findings",
                        to="scans.vulnerability",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
