# Generated by Django 5.1.4 on 2026-08-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0002_scan_failure_reason_target_scan_target_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="celery_task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="scan",
            name="options",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="scan",
            name="phase",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="scan",
            name="progress",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="finding",
            name="category",
            field=models.CharField(
                choices=[
                    ("software", "Software (CVE)"),
                    ("service", "Serviço de rede"),
                    ("network", "Rede"),
                    ("credential", "Credencial"),
                    ("tls", "TLS"),
                    ("certificate", "Certificado"),
                    ("dns", "DNS"),
                    ("email-security", "Segurança de e-mail"),
                    ("subdomain", "Subdomínio"),
                    ("web-headers", "Headers HTTP"),
                    ("cookie", "Cookie"),
                    ("cors", "CORS"),
                    ("exposure", "Exposição"),
                    ("http-method", "Método HTTP"),
                    ("injection", "Injeção"),
                ],
                max_length=50,
            ),
        ),
    ]
